name: Build and Release

on:
  push:
    tags:
      - 'v*' # 触发工作流的标签，例如 v1.0, v1.2.3

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # 与 pyproject.toml 中指定的版本一致

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e . --group dev

      - name: Build with PyInstaller
        run: pyinstaller --name ddns --onefile --noconsole main.py

      - name: Prepare release package
        run: |
          mkdir release
          copy dist\ddns.exe release\
          copy config.example.toml release\
          cd release
          Compress-Archive -Path * -DestinationPath ..\ddns-windows-${{ github.ref_name }}.zip
          cd ..

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ddns-windows-${{ github.ref_name }}.zip
          body: "Automated release for ${{ github.ref_name }}"
          name: "Release ${{ github.ref_name }}"